<?php

namespace Database\Seeders;

use App\Models\Contract;
use Illuminate\Database\Seeder;

class ContractSeeder extends Seeder
{
    public function run(): void
    {
        $contracts = [
            // Arqueros
            [
                'nombre_completo'      => 'Rodrigo Rey',
                'fecha_firma'          => '2023-07-01',
                'fecha_caducidad'      => '2025-12-31',
                'porcentaje_pase_club' => 100.00,
                'salario_estimado'     => 35000.00,
                'moneda'              => 'USD',
                'oficial'             => true,
                'clausulas'           => json_encode(['Cláusula de rescisión: USD 5M']),
                'links'               => json_encode([]),
            ],
            [
                'nombre_completo'      => 'Lucas Rodríguez',
                'fecha_firma'          => '2024-01-01',
                'fecha_caducidad'      => '2025-06-30',
                'porcentaje_pase_club' => 100.00,
                'salario_estimado'     => 8000.00,
                'moneda'              => 'USD',
                'oficial'             => false,
                'clausulas'           => json_encode([]),
                'links'               => json_encode([]),
            ],

            // Defensores
            [
                'nombre_completo'      => 'Sergio Barreto',
                'fecha_firma'          => '2024-01-15',
                'fecha_caducidad'      => '2026-06-30',
                'porcentaje_pase_club' => 80.00,
                'salario_estimado'     => 25000.00,
                'moneda'              => 'USD',
                'oficial'             => false,
                'clausulas'           => json_encode([]),
                'links'               => json_encode([]),
            ],
            [
                'nombre_completo'      => 'Emanuel Mammana',
                'fecha_firma'          => '2024-06-15',
                'fecha_caducidad'      => '2026-12-31',
                'porcentaje_pase_club' => 100.00,
                'salario_estimado'     => 30000.00,
                'moneda'              => 'USD',
                'oficial'             => false,
                'clausulas'           => json_encode(['Opción de compra definitiva']),
                'links'               => json_encode([]),
            ],
            [
                'nombre_completo'      => 'Alexander Barboza',
                'fecha_firma'          => '2023-01-01',
                'fecha_caducidad'      => '2025-06-30',
                'porcentaje_pase_club' => 70.00,
                'salario_estimado'     => 18000.00,
                'moneda'              => 'USD',
                'oficial'             => false,
                'clausulas'           => json_encode([]),
                'links'               => json_encode([]),
            ],
            [
                'nombre_completo'      => 'Lucas González',
                'fecha_firma'          => '2022-07-01',
                'fecha_caducidad'      => '2024-06-30',
                'porcentaje_pase_club' => 60.00,
                'salario_estimado'     => null,
                'moneda'              => null,
                'oficial'             => false,
                'clausulas'           => json_encode(['Préstamo con opción de compra: USD 5M']),
                'links'               => json_encode([]),
            ],
            [
                'nombre_completo'      => 'Gastón Togni',
                'fecha_firma'          => '2023-02-01',
                'fecha_caducidad'      => '2025-06-30',
                'porcentaje_pase_club' => 100.00,
                'salario_estimado'     => 12000.00,
                'moneda'              => 'USD',
                'oficial'             => false,
                'clausulas'           => json_encode([]),
                'links'               => json_encode([]),
            ],
            [
                'nombre_completo'      => 'Fabricio Bustos',
                'fecha_firma'          => '2024-07-01',
                'fecha_caducidad'      => '2026-06-30',
                'porcentaje_pase_club' => 100.00,
                'salario_estimado'     => 22000.00,
                'moneda'              => 'USD',
                'oficial'             => true,
                'clausulas'           => json_encode(['Cláusula de rescisión: USD 3M']),
                'links'               => json_encode([]),
            ],

            // Mediocampistas
            [
                'nombre_completo'      => 'Iván Marcone',
                'fecha_firma'          => '2023-08-01',
                'fecha_caducidad'      => '2025-06-30',
                'porcentaje_pase_club' => 50.00,
                'salario_estimado'     => null,
                'moneda'              => null,
                'oficial'             => false,
                'clausulas'           => json_encode(['Opción de compra: USD 2M']),
                'links'               => json_encode([]),
            ],
            [
                'nombre_completo'      => 'Alan Soñora',
                'fecha_firma'          => '2023-07-15',
                'fecha_caducidad'      => '2026-12-31',
                'porcentaje_pase_club' => 90.00,
                'salario_estimado'     => 20000.00,
                'moneda'              => 'USD',
                'oficial'             => false,
                'clausulas'           => json_encode([]),
                'links'               => json_encode([]),
            ],
            [
                'nombre_completo'      => 'Javier Altamirano',
                'fecha_firma'          => '2022-01-01',
                'fecha_caducidad'      => '2024-12-31',
                'porcentaje_pase_club' => 80.00,
                'salario_estimado'     => 15000.00,
                'moneda'              => 'USD',
                'oficial'             => false,
                'clausulas'           => json_encode([]),
                'links'               => json_encode([]),
            ],
            [
                'nombre_completo'      => 'Carlos Briasco',
                'fecha_firma'          => '2024-02-01',
                'fecha_caducidad'      => '2026-06-30',
                'porcentaje_pase_club' => 100.00,
                'salario_estimado'     => 16000.00,
                'moneda'              => 'USD',
                'oficial'             => false,
                'clausulas'           => json_encode([]),
                'links'               => json_encode([]),
            ],
            [
                'nombre_completo'      => 'Lucas Romero',
                'fecha_firma'          => '2023-06-01',
                'fecha_caducidad'      => '2025-12-31',
                'porcentaje_pase_club' => 100.00,
                'salario_estimado'     => 14000.00,
                'moneda'              => 'USD',
                'oficial'             => false,
                'clausulas'           => json_encode([]),
                'links'               => json_encode([]),
            ],
            [
                'nombre_completo'      => 'Kevin Lomónaco',
                'fecha_firma'          => '2024-02-10',
                'fecha_caducidad'      => '2027-06-30',
                'porcentaje_pase_club' => 70.00,
                'salario_estimado'     => 18000.00,
                'moneda'              => 'USD',
                'oficial'             => false,
                'clausulas'           => json_encode([]),
                'links'               => json_encode([]),
            ],

            // Delanteros
            [
                'nombre_completo'      => 'Silvio Romero',
                'fecha_firma'          => '2022-08-01',
                'fecha_caducidad'      => '2025-06-30',
                'porcentaje_pase_club' => 100.00,
                'salario_estimado'     => 40000.00,
                'moneda'              => 'USD',
                'oficial'             => true,
                'clausulas'           => json_encode(['Cláusula de rescisión: USD 8M']),
                'links'               => json_encode([]),
            ],
            [
                'nombre_completo'      => 'Leandro Fernández',
                'fecha_firma'          => '2021-06-01',
                'fecha_caducidad'      => '2024-06-30',
                'porcentaje_pase_club' => 100.00,
                'salario_estimado'     => 28000.00,
                'moneda'              => 'USD',
                'oficial'             => true,
                'clausulas'           => json_encode([]),
                'links'               => json_encode([]),
            ],
            [
                'nombre_completo'      => 'Jonatan Báez',
                'fecha_firma'          => '2022-01-01',
                'fecha_caducidad'      => '2024-06-30',
                'porcentaje_pase_club' => 90.00,
                'salario_estimado'     => 22000.00,
                'moneda'              => 'USD',
                'oficial'             => false,
                'clausulas'           => json_encode([]),
                'links'               => json_encode([]),
            ],
            [
                'nombre_completo'      => 'Joaquín Laso',
                'fecha_firma'          => '2023-01-01',
                'fecha_caducidad'      => '2025-12-31',
                'porcentaje_pase_club' => 100.00,
                'salario_estimado'     => 10000.00,
                'moneda'              => 'USD',
                'oficial'             => false,
                'clausulas'           => json_encode([]),
                'links'               => json_encode([]),
            ],
            [
                'nombre_completo'      => 'Alexis Canelo',
                'fecha_firma'          => '2024-07-01',
                'fecha_caducidad'      => '2027-06-30',
                'porcentaje_pase_club' => 60.00,
                'salario_estimado'     => 12000.00,
                'moneda'              => 'USD',
                'oficial'             => false,
                'clausulas'           => json_encode(['Cláusula de compra por terceros: USD 4M']),
                'links'               => json_encode([]),
            ],
            [
                'nombre_completo'      => 'Facundo Pumpido',
                'fecha_firma'          => '2025-01-15',
                'fecha_caducidad'      => '2026-12-31',
                'porcentaje_pase_club' => 100.00,
                'salario_estimado'     => 9000.00,
                'moneda'              => 'USD',
                'oficial'             => false,
                'clausulas'           => json_encode([]),
                'links'               => json_encode([]),
            ],
        ];

        foreach ($contracts as $contract) {
            Contract::create($contract);
        }
    }
}
