<?php

namespace Database\Seeders;

use App\Models\EconomyRecord;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class EconomyRecordSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        // Helper para obtener el primer día de un mes relativo al actual
        $month = fn(int $offset) => $now->copy()->startOfMonth()->addMonths($offset)->toDateString();
        // Helper para una fecha específica dentro de un mes relativo
        $date  = fn(int $offset, int $day) => $now->copy()->startOfMonth()->addMonths($offset)->setDay($day)->toDateString();

        $records = [
            // =====================================================================
            // PASADO (~2 años atrás hasta hoy)
            // =====================================================================

            // Hace ~24 meses
            [
                'descripcion'      => 'Derechos TV - Cuota trimestral LPF',
                'tipo'             => 'cobro',
                'monto'            => 280000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $month(-24),
                'oficial'          => true,
                'confidence_level' => 'high',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Pago de salarios - Plantel profesional',
                'tipo'             => 'pago',
                'monto'            => 380000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(-24, 28),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Venta de Lucas González al Udinese (IT) - cuota final',
                'tipo'             => 'cobro',
                'monto'            => 2000000.00,
                'moneda'           => 'USD',
                'fecha'            => $date(-23, 10),
                'oficial'          => true,
                'confidence_level' => 'high',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Pago de salarios - Plantel profesional',
                'tipo'             => 'pago',
                'monto'            => 385000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(-23, 28),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],

            // Hace ~21 meses
            [
                'descripcion'      => 'Derechos TV - Cuota trimestral LPF',
                'tipo'             => 'cobro',
                'monto'            => 310000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $month(-21),
                'oficial'          => true,
                'confidence_level' => 'high',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Patrocinio Quilmes - Temporada',
                'tipo'             => 'cobro',
                'monto'            => 1200000.00,
                'moneda'           => 'USD',
                'fecha'            => $date(-21, 5),
                'oficial'          => true,
                'confidence_level' => 'high',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Venta de Jonatan Báez al Cruz Azul (MX)',
                'tipo'             => 'cobro',
                'monto'            => 3500000.00,
                'moneda'           => 'USD',
                'fecha'            => $date(-20, 5),
                'oficial'          => false,
                'confidence_level' => 'medium',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Compra de Alan Soñora (Unión de Santa Fe)',
                'tipo'             => 'pago',
                'monto'            => 800000.00,
                'moneda'           => 'USD',
                'fecha'            => $date(-20, 15),
                'oficial'          => false,
                'confidence_level' => 'medium',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Pago de salarios - Plantel profesional',
                'tipo'             => 'pago',
                'monto'            => 410000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(-20, 28),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],

            // Hace ~18 meses
            [
                'descripcion'      => 'Derechos TV - Cuota trimestral LPF',
                'tipo'             => 'cobro',
                'monto'            => 340000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $month(-18),
                'oficial'          => true,
                'confidence_level' => 'high',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Recaudación partido vs San Lorenzo - Liga Profesional',
                'tipo'             => 'cobro',
                'monto'            => 72000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(-17, 14),
                'oficial'          => true,
                'confidence_level' => 'high',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Multa AFA por incidentes en clásico',
                'tipo'             => 'pago',
                'monto'            => 18000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(-17, 20),
                'oficial'          => true,
                'confidence_level' => 'high',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Pago de salarios - Plantel profesional',
                'tipo'             => 'pago',
                'monto'            => 430000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(-17, 28),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Mantenimiento y obras estadio Libertadores de América',
                'tipo'             => 'pago',
                'monto'            => 250000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(-16, 15),
                'oficial'          => false,
                'confidence_level' => 'medium',
                'links'            => json_encode([]),
            ],

            // Hace ~15 meses
            [
                'descripcion'      => 'Derechos TV - Cuota trimestral LPF',
                'tipo'             => 'cobro',
                'monto'            => 320000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $month(-15),
                'oficial'          => true,
                'confidence_level' => 'high',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Venta de Leandro Fernández al Toluca (MX)',
                'tipo'             => 'cobro',
                'monto'            => 4500000.00,
                'moneda'           => 'USD',
                'fecha'            => $date(-14, 15),
                'oficial'          => true,
                'confidence_level' => 'high',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Compra de Kevin Lomónaco',
                'tipo'             => 'pago',
                'monto'            => 1200000.00,
                'moneda'           => 'USD',
                'fecha'            => $date(-13, 10),
                'oficial'          => false,
                'confidence_level' => 'medium',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Patrocinio principal Puma - Temporada',
                'tipo'             => 'cobro',
                'monto'            => 1800000.00,
                'moneda'           => 'USD',
                'fecha'            => $date(-13, 1),
                'oficial'          => true,
                'confidence_level' => 'high',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Pago de salarios - Plantel profesional',
                'tipo'             => 'pago',
                'monto'            => 480000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(-13, 28),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],

            // Hace ~12 meses
            [
                'descripcion'      => 'Derechos TV - Cuota trimestral LPF',
                'tipo'             => 'cobro',
                'monto'            => 320000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $month(-12),
                'oficial'          => true,
                'confidence_level' => 'high',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Recaudación partido vs Racing - Clásico de Avellaneda',
                'tipo'             => 'cobro',
                'monto'            => 85000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(-11, 5),
                'oficial'          => true,
                'confidence_level' => 'high',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Pago de salarios - Plantel profesional',
                'tipo'             => 'pago',
                'monto'            => 450000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(-11, 28),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Venta de Javier Altamirano al Sporting de Lisboa (PT)',
                'tipo'             => 'cobro',
                'monto'            => 6000000.00,
                'moneda'           => 'USD',
                'fecha'            => $date(-11, 1),
                'oficial'          => true,
                'confidence_level' => 'high',
                'links'            => json_encode([]),
            ],

            // Hace ~9 meses
            [
                'descripcion'      => 'Derechos TV - Cuota trimestral LPF',
                'tipo'             => 'cobro',
                'monto'            => 350000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $month(-9),
                'oficial'          => true,
                'confidence_level' => 'high',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Recaudación Copa de la Liga - Fase de grupos',
                'tipo'             => 'cobro',
                'monto'            => 52000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(-8, 20),
                'oficial'          => true,
                'confidence_level' => 'high',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Pago de salarios - Plantel profesional',
                'tipo'             => 'pago',
                'monto'            => 500000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(-8, 28),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Venta parcial pase de Alexis Canelo al exterior',
                'tipo'             => 'cobro',
                'monto'            => 900000.00,
                'moneda'           => 'USD',
                'fecha'            => $date(-8, 20),
                'oficial'          => false,
                'confidence_level' => 'medium',
                'links'            => json_encode([]),
            ],

            // Hace ~6 meses
            [
                'descripcion'      => 'Derechos TV - Cuota trimestral LPF',
                'tipo'             => 'cobro',
                'monto'            => 380000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $month(-6),
                'oficial'          => true,
                'confidence_level' => 'high',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Recaudación partido vs Boca Juniors - LPF',
                'tipo'             => 'cobro',
                'monto'            => 110000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(-5, 8),
                'oficial'          => true,
                'confidence_level' => 'high',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Multa AFA por demora en pagos de salarios',
                'tipo'             => 'pago',
                'monto'            => 25000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(-5, 15),
                'oficial'          => true,
                'confidence_level' => 'high',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Venta de Silvio Romero al Al-Ettifaq (SA)',
                'tipo'             => 'cobro',
                'monto'            => 5200000.00,
                'moneda'           => 'USD',
                'fecha'            => $date(-5, 28),
                'oficial'          => false,
                'confidence_level' => 'medium',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Pago de salarios - Plantel profesional',
                'tipo'             => 'pago',
                'monto'            => 560000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(-4, 28),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Deuda con AFIP - Plan de pagos cuota',
                'tipo'             => 'pago',
                'monto'            => 120000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(-4, 10),
                'oficial'          => true,
                'confidence_level' => 'high',
                'links'            => json_encode([]),
            ],

            // Hace ~3 meses
            [
                'descripcion'      => 'Derechos TV - Cuota trimestral LPF',
                'tipo'             => 'cobro',
                'monto'            => 420000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $month(-3),
                'oficial'          => true,
                'confidence_level' => 'high',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Recaudación Copa Argentina - Cuartos de Final',
                'tipo'             => 'cobro',
                'monto'            => 65000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(-2, 12),
                'oficial'          => true,
                'confidence_level' => 'high',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Pago de salarios - Plantel profesional',
                'tipo'             => 'pago',
                'monto'            => 580000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(-2, 28),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Mantenimiento predio de Villa Domínico',
                'tipo'             => 'pago',
                'monto'            => 180000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(-2, 20),
                'oficial'          => false,
                'confidence_level' => 'medium',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Patrocinio secundario - acuerdo comercial',
                'tipo'             => 'cobro',
                'monto'            => 400000.00,
                'moneda'           => 'USD',
                'fecha'            => $date(-1, 15),
                'oficial'          => false,
                'confidence_level' => 'medium',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Pago de salarios - Plantel profesional',
                'tipo'             => 'pago',
                'monto'            => 620000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(-1, 28),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],

            // =====================================================================
            // FUTURO (~1 mes adelante hasta +24 meses)
            // =====================================================================

            // Próximo mes
            [
                'descripcion'      => 'Derechos TV - Cuota trimestral LPF (proyectado)',
                'tipo'             => 'cobro',
                'monto'            => 450000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $month(1),
                'oficial'          => false,
                'confidence_level' => 'medium',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Pago de salarios - Plantel profesional (proyectado)',
                'tipo'             => 'pago',
                'monto'            => 650000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(1, 28),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],

            // +2 meses
            [
                'descripcion'      => 'Recaudación partido vs Racing - Clásico de Avellaneda (proyectado)',
                'tipo'             => 'cobro',
                'monto'            => 120000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(2, 9),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Pago de salarios - Plantel profesional (proyectado)',
                'tipo'             => 'pago',
                'monto'            => 660000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(2, 28),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],

            // +3 meses
            [
                'descripcion'      => 'Derechos TV - Cuota trimestral LPF (proyectado)',
                'tipo'             => 'cobro',
                'monto'            => 460000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $month(3),
                'oficial'          => false,
                'confidence_level' => 'medium',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Deuda con AFIP - Plan de pagos cuota (proyectado)',
                'tipo'             => 'pago',
                'monto'            => 120000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(3, 10),
                'oficial'          => true,
                'confidence_level' => 'high',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Pago de salarios - Plantel profesional (proyectado)',
                'tipo'             => 'pago',
                'monto'            => 670000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(3, 28),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],

            // +4 meses
            [
                'descripcion'      => 'Patrocinio principal Puma - renovación anual (proyectado)',
                'tipo'             => 'cobro',
                'monto'            => 2000000.00,
                'moneda'           => 'USD',
                'fecha'            => $date(4, 1),
                'oficial'          => false,
                'confidence_level' => 'medium',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Pago de salarios - Plantel profesional (proyectado)',
                'tipo'             => 'pago',
                'monto'            => 680000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(4, 28),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],

            // +5 meses
            [
                'descripcion'      => 'Recaudación Copa de la Liga - Semifinal (proyectado)',
                'tipo'             => 'cobro',
                'monto'            => 90000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(5, 15),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Pago de salarios - Plantel profesional (proyectado)',
                'tipo'             => 'pago',
                'monto'            => 690000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(5, 28),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],

            // +6 meses
            [
                'descripcion'      => 'Derechos TV - Cuota trimestral LPF (proyectado)',
                'tipo'             => 'cobro',
                'monto'            => 480000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $month(6),
                'oficial'          => false,
                'confidence_level' => 'medium',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Venta proyectada de juvenil al exterior - cuota 1/2',
                'tipo'             => 'cobro',
                'monto'            => 1500000.00,
                'moneda'           => 'USD',
                'fecha'            => $date(6, 20),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Deuda con AFIP - Plan de pagos cuota (proyectado)',
                'tipo'             => 'pago',
                'monto'            => 120000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(6, 10),
                'oficial'          => true,
                'confidence_level' => 'high',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Pago de salarios - Plantel profesional (proyectado)',
                'tipo'             => 'pago',
                'monto'            => 710000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(6, 28),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],

            // +9 meses
            [
                'descripcion'      => 'Derechos TV - Cuota trimestral LPF (proyectado)',
                'tipo'             => 'cobro',
                'monto'            => 500000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $month(9),
                'oficial'          => false,
                'confidence_level' => 'medium',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Pago de salarios - Plantel profesional (proyectado)',
                'tipo'             => 'pago',
                'monto'            => 750000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(9, 28),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Recaudación partido vs Boca Juniors - LPF (proyectado)',
                'tipo'             => 'cobro',
                'monto'            => 130000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(10, 5),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Deuda con AFIP - Plan de pagos cuota (proyectado)',
                'tipo'             => 'pago',
                'monto'            => 120000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(9, 10),
                'oficial'          => true,
                'confidence_level' => 'high',
                'links'            => json_encode([]),
            ],

            // +12 meses
            [
                'descripcion'      => 'Derechos TV - Cuota trimestral LPF (proyectado)',
                'tipo'             => 'cobro',
                'monto'            => 520000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $month(12),
                'oficial'          => false,
                'confidence_level' => 'medium',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Patrocinio principal - renovación anual (proyectado)',
                'tipo'             => 'cobro',
                'monto'            => 2200000.00,
                'moneda'           => 'USD',
                'fecha'            => $date(12, 1),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Pago de salarios - Plantel profesional (proyectado)',
                'tipo'             => 'pago',
                'monto'            => 800000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(12, 28),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Venta proyectada de juvenil al exterior - cuota 2/2',
                'tipo'             => 'cobro',
                'monto'            => 1500000.00,
                'moneda'           => 'USD',
                'fecha'            => $date(13, 20),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],

            // +15 meses
            [
                'descripcion'      => 'Derechos TV - Cuota trimestral LPF (proyectado)',
                'tipo'             => 'cobro',
                'monto'            => 550000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $month(15),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Pago de salarios - Plantel profesional (proyectado)',
                'tipo'             => 'pago',
                'monto'            => 850000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(15, 28),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],

            // +18 meses
            [
                'descripcion'      => 'Derechos TV - Cuota trimestral LPF (proyectado)',
                'tipo'             => 'cobro',
                'monto'            => 580000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $month(18),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Patrocinio principal - renovación anual (proyectado)',
                'tipo'             => 'cobro',
                'monto'            => 2400000.00,
                'moneda'           => 'USD',
                'fecha'            => $date(18, 1),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Pago de salarios - Plantel profesional (proyectado)',
                'tipo'             => 'pago',
                'monto'            => 900000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(18, 28),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],

            // +21 meses
            [
                'descripcion'      => 'Derechos TV - Cuota trimestral LPF (proyectado)',
                'tipo'             => 'cobro',
                'monto'            => 610000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $month(21),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Pago de salarios - Plantel profesional (proyectado)',
                'tipo'             => 'pago',
                'monto'            => 950000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(21, 28),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],

            // +24 meses
            [
                'descripcion'      => 'Derechos TV - Cuota trimestral LPF (proyectado)',
                'tipo'             => 'cobro',
                'monto'            => 640000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $month(24),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Patrocinio principal - renovación anual (proyectado)',
                'tipo'             => 'cobro',
                'monto'            => 2600000.00,
                'moneda'           => 'USD',
                'fecha'            => $date(24, 1),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],
            [
                'descripcion'      => 'Pago de salarios - Plantel profesional (proyectado)',
                'tipo'             => 'pago',
                'monto'            => 1000000000.00,
                'moneda'           => 'ARS',
                'fecha'            => $date(24, 28),
                'oficial'          => false,
                'confidence_level' => 'low',
                'links'            => json_encode([]),
            ],
        ];

        foreach ($records as $record) {
            EconomyRecord::create($record);
        }
    }
}
